### PR TITLE
implement peerPicker with grpc

### PR DESCRIPTION
**Pull request by hsinhoyeh**
this PR implements GRPCPool which follows PeerPicker interface but the implementation is based on google's grpc.
there are some issues which haven't been addressed in this PR, we could have them in a separated PR

==1. interface: 
grpc uses protobuf version 3, the generated stub is different with the one generated before. Like 
v2:

```
type GetRequest struct {
        Group            *string `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
        Key              *string `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
        XXX_unrecognized []byte  `json:"-"`
}
```

v3:

```
type GetRequest struct {
       Group string `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
       Key   string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}
```

If we switched to protoc 3 directly, we may break something. so we just workaround this. The interface is untouched.

==2. Context: 
right now the context used in groupcache is self-defined Context

```
// ProtoGetter is the interface that must be implemented by a peer.
type ProtoGetter interface {
        Get(context Context, in *pb.GetRequest, out *pb.GetResponse) error
}
```

and grpc use "golang.org/x/net/context" as default context. so we can pick one.

==3. performance comparison: 
we will do that after the implementation sounds good.

### CODE REVIEW

**Comment by bradfitz** [comment]
I only want to look at a single commit (not a stack of 3) and I think this should live in a new child package, not be part of the existing package.

Also, have you signed a CLA?

**Comment by hsinhoyeh** [comment]
Hi

I have squashed the commits into one and also moved them into grpc subpackage.
I also signed a CLA.
thanks

**Comment by xiang90** [comment]
@hsinhoyeh Have you got any benchmark result compared to http? @bradfitz Are you interested in getting this merged into groupcache?

**Comment by hsinhoyeh** [comment]
@xiang90 not yet. will do that if I have some bandwidth.

**Comment by bradfitz** [comment]
Can this peer-picker live elsewhere on github, outside of this repo?

**Comment by bradfitz** [comment]
I'm going to close this for now, assuming it's expired.

I have the googlebot doing CLA checks here now, so I can take contributions if you're still interested in pursuing this. Let me know or just reopen it if you are.

**Pull request closed without merging**
